LDWS : main.cpp ImageTransformation.cpp ImageTransformation.h LaneAnalysis.cpp LaneAnalysis.h LDWS.cpp LDWS.h ROI.cpp ROI.h StaticImage.cpp StaticImage.h StaticVideo.cpp StaticVideo.h LiveVideo.cpp LiveVideo.h

	g++ -std=c++11 ImageTransformation.cpp LaneAnalysis.cpp LDWS.cpp ROI.cpp LiveVideo.cpp StaticImage.cpp StaticVideo.cpp main.cpp -o LDWS `pkg-config --cflags --libs opencv4` 